baseUrl= 'https://simonsmith.io/'
languageCode = "en-gb"
title = '&ndash; simonsmith.io'

[permalinks]
  blog = "/:slug"

pygmentsUseClasses = false
pygmentsCodeFences = true
PygmentsStyle = 'friendly'
