title: '&ndash; simonsmith.io'
permalinks:
  blog: /:slug
pygmentsUseClasses: true
pygmentsCodeFences: true
metaDataFormat: 'yaml'
paginate: 15
menu:
  main:
    - Name: "CV"
      Identifier: "cv"
      URL: "/cv/"
    - Name: "Projects"
      Identifier: "projects"
      URL: "/projects/"
